### ISSUE TITLE
 how much time bruu. Pls fix this error 

### ISSUE THREAD

**Issue by SHADow5446** [mukul500/AnimeXStream#128]

**Comment by 7thghoul** [comment]
Please stop spamming issues. We know you are desperate to watch animes no matter what since KA and many other sites were banned. Have patience, he knows the errors and what's causing it. The app is free to use, he doesn't earns from it. So, he definitely has other job to focus on. We highly appreciate your understanding.

**Comment by mukul500** [comment]
Please Check Latest Release [v0.2.4](https://github.com/mukul500/AnimeXStream)
