### ISSUE TITLE
App keeps stopping

### ISSUE THREAD

**Issue by Izurieru** [mukul500/AnimeXStream#36]
I have been using this app for the last month ad when I tried to use it again today, it just crashes. I tried reinstalling and using an older version but it still has the same problem.

**Comment by frytkisasmaczne** [comment]
#metoo

**Comment by HarshaKosuru** [comment]
Same here

**Comment by DoggoOfSpeed** [comment]
Welp #metoo

**Comment by frytkisasmaczne** [comment]
i guess my `logcat | grep anime > xd.txt` is better than nothing [https://rentry.co/zvqcq](https://rentry.co/zvqcq)

**Comment by mukul500** [comment]
Who's  app is crashing. Please mention following details.

App version-
Android version-
Device -
Country -
City-

**Comment by mukul500** [comment]
Due to changes from the GogoAnime website. The app is not able to parse data from it. That's why it's crashing. So I am working on it. Soon provide new update

**Comment by mukul500** [comment]
Update: Actually it's not parsing problem. It is caused by Gogoanime backend. Please check if you can access https://www.gogoanime.io/ 

If you get response "The argument is not initialized or iterable()". This means you can't access the app too. You need to wait for the issue to resolve from their end.

In the end, this app is just a parser. If they don't resolve it within 2 days. I will switch host

**Comment by mukul500** [comment]
Issue has been fixed.

**Comment by frytkisasmaczne** [comment]
it just started happening to me again. i'm gonna check on another phone, but check tooplz.
also, this time i can load gogoanime main page in the browser fine

**Comment by Izurieru** [comment]
same here. I can load gogoanime.io just fine but the app still keeps stopping

**Comment by frytkisasmaczne** [comment]
my logcat from clean install https://rentry.co/z6uxt
