### ISSUE TITLE
[SUGGESTION] Skip intro button in video player

### ISSUE THREAD

**Issue by axel05869** [mukul500/AnimeXStream#45]
It will be convenient if you add a skip intro button for anime.

As I remember all of the anime intros are about 80+ seconds long. so to implement it, you just need to put a button that seek video about 80 sec. when clicked and that will skip the intro.

**Comment by GoluLiliput** [comment]
This cannot be implemented because the intro timing officially varies from 70 to 110 or even sometimes 120 seconds. That makes an average intro timing of 90 secs.
So based on what anime you are watching this feauture implementation is not possible. This is possible in Netflix and few more services because they have monitored each of their series and have official record how long the intros are there. Please don't get inspired from those services. It's impossible to calculate even 5% of all the anime present out there. I hope u understand

**Comment by Mrfiregem** [comment]
The browser extension MALSync has this feature. It defaults to skip 85 seconds when the user presses a key combination, but allows the user to change it in the settings.

**Comment by rickninja765** [comment]
> This cannot be implemented because the intro timing officially varies from 70 to 110 or even sometimes 120 seconds. That makes an average intro timing of 90 secs.
> So based on what anime you are watching this feauture implementation is not possible. This is possible in Netflix and few more services because they have monitored each of their series and have official record how long the intros are there. Please don't get inspired from those services. It's impossible to calculate even 5% of all the anime present out there. I hope u understand

Even For Youtube One extension is available called SponsorBlock, That uses Users Input for specific videos and skip the Sponsors and Database that stored information of about videos.
So One Developer implemented that Extension in newpipe called Newpipe Sponsorblock app. It Works like a charm. If You want to try.

**Comment by Matterhorn56** [comment]
I suppose a similar feature could be implemented where the skip time can be set per anime.
The default would be zero, and no skip intro button would be displayed on the player.
Skip time can be set on each anime's page (top right maybe).

**Comment by mukul500** [comment]
Please see #76 for app suggestions
