### ISSUE TITLE
[Suggestion] Add the option to play with an external player

### ISSUE THREAD

**Issue by Erunn** [mukul500/AnimeXStream#56]
This would be very convenient so user can play with vlc, and by doing that, user has the capability to cast to tv for example. Thanks in advance.

**Comment by justdvnsh** [comment]
@Erunn . Currently I don't think it could be done, as far as I know. Since, we can open the VLC player using intent, yet when passing the url, it would not take it as a video url, since in the app, the page is being parsed to fetch the content. I tried using vlc, but the streaming was not taking place.

**Comment by JPBuenaventura** [comment]
I've tried passing the m3u8 url as intent to MX player and it can play it although in max quality (720p/1080p depending on source)
Casting also works using bubbleupnp (quality is still in max)

External play/Casting is possible but not on all video apps :(

**Comment by justdvnsh** [comment]
@JPBuenaventura Yeah ! True that. I was particularly stating about VLC media player.

**Comment by mukul500** [comment]
Please see #76 for app suggestions
